### ISSUE TITLE
Plugin doesn't work.

### ISSUE THREAD

**Issue by Ozaxx** [SammCheese/powercord-sauce#2]
![image](https://user-images.githubusercontent.com/69100788/150684512-4de7a9c7-bb93-4a15-a5cd-10eeaac86aff.png)

**Comment by Ozaxx** [comment]
Canary 111712 (a7dd479) 
Host 1.0.43 
Windows 10 64-Bit (10.0.19042)
Powercord v2 (12de9dc)

**Comment by SammCheese** [comment]
Appears to work normally for me, Its very likely an issue with your internet or service provider

**Comment by SammCheese** [comment]
Closed
